TrajectoryPlannerROS:
  
  #Robot parameters
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 1.0

  max_vel_x : 2.0
  # escape_vel: -2.0
  max_vel_theta : 1.0
  min_vel_theta : -1.0
  min_in_place_vel_theta: 0.4
  
  holonomic_robot: false

  #Goal parameters
  yaw_goal_tolerance: 0.087 #0.087
  xy_goal_tolerance: 0.1

  #Trajectory Scoring Parameters
  # path_distance_bias: 2.8
  # goal_distance_bias: 0.8

  #Forward Simualtion
  # sim_time: 1.0
  # vx_samples: 10
  # vtheta_samples: 21