local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base
  update_frequency: 4.0 #before 5.0
  publish_frequency: 0.5 #before 2.0
  static_map: false
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.05 #increase to for higher res 0.025
  
  cost_scaling_factor: 2.0
  inflation_radius: 0.3

  # local_costmap:
  # global_frame: odom
  # robot_base_frame: ebot_base
  # update_frequency: 4 #before 5.0
  # publish_frequency: 0.5 #before 2.0
  # static_map: false
  # rolling_window: true
  # width: 2.3
  # height: 2.3
  # resolution: 0.05 #increase to for higher res 0.025
  
  # cost_scaling_factor: 3.0
  # inflation_radius: 0.15