TrajectoryPlannerROS:
  max_vel_x: 3
  min_vel_x: 0.01
  max_vel_theta: 2
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 2
  acc_lim_x: 1
  acc_lim_y: 0.5

  yaw_goal_tolerance : 0.6
  xy_goal_tolerance : 0.2
  holonomic_robot: false

# TrajectoryPlannerROS:
#   max_vel_x: 20
#   min_vel_x: 0.05

#   max_vel_theta: 1.2
#   min_vel_theta: -1.0

#   min_in_place_vel_theta: 0.5

#   acc_lim_theta: 0.2
#   acc_lim_x: 3 # Before 2.5
#   acc_lim_y: 0

  
#   holonomic_robot: false

#   sim_time: 3.0
#   yaw_goal_tolerance : 0.6
#   xy_goal_tolerance : 0.2
#   path_distance_bias : 40

#   occdist_scale : 0.05 #Default 0.01
#   latch_xy_goal_tolerance : false

#   vx_samples: 20
#   vy_samples: 0
#   vtheta_samples: 40
